name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build all packages
        run: npm run build
        env:
          TURBO_TOKEN: pBy4qaoqkTuTfnA1Q0v2qiDj
          TURBO_TEAM: giovanny-fialhos-projects

      - name: Build Storybook
        working-directory: ./packages/docs
        run: npm run build

      - name: Debug Build Output
        working-directory: ./packages/docs
        run: |
          echo "Listing files in storybook-static"
          ls -la ./storybook-static
          echo "Preview of index.html"
          head -n 20 ./storybook-static/index.html

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: touch storybook-static/.nojekyll && npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
